# Generated by Django 2.0.2 on 2018-09-03 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squashApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='playerData',
            fields=[
                ('playerId', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(max_length=30, verbose_name='last name')),
                ('country', models.CharField(max_length=30, verbose_name='country')),
            ],
        ),
    ]
