# Generated by Django 2.0.2 on 2018-10-12 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squashApp', '0003_auto_20180904_2205'),
    ]

    operations = [
        migrations.RenameField(
            model_name='videodata',
            old_name='processedVideoFile',
            new_name='player1HeatMapVideoFile',
        ),
        migrations.AddField(
            model_name='videodata',
            name='player1DistanceTravelled',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='videodata',
            name='player1HeatMapImage',
            field=models.FileField(null=True, upload_to='processedVideos/', verbose_name=''),
        ),
        migrations.AddField(
            model_name='videodata',
            name='player1StringLineImage',
            field=models.FileField(null=True, upload_to='processedVideos/', verbose_name=''),
        ),
        migrations.AddField(
            model_name='videodata',
            name='player1StringLineVideoFile',
            field=models.FileField(null=True, upload_to='processedVideos/', verbose_name=''),
        ),
        migrations.AddField(
            model_name='videodata',
            name='player2DistanceTravelled',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='videodata',
            name='player2HeatMapImage',
            field=models.FileField(null=True, upload_to='processedVideos/', verbose_name=''),
        ),
        migrations.AddField(
            model_name='videodata',
            name='player2HeatMapVideoFile',
            field=models.FileField(null=True, upload_to='processedVideos/', verbose_name=''),
        ),
        migrations.AddField(
            model_name='videodata',
            name='player2StringLineImage',
            field=models.FileField(null=True, upload_to='processedVideos/', verbose_name=''),
        ),
        migrations.AddField(
            model_name='videodata',
            name='player2StringLineVideoFile',
            field=models.FileField(null=True, upload_to='processedVideos/', verbose_name=''),
        ),
    ]
