# Generated by Django 2.0.2 on 2018-10-12 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squashApp', '0006_auto_20181012_1126'),
    ]

    operations = [
        migrations.AddField(
            model_name='videodata',
            name='player1TimeInT',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='videodata',
            name='player2TimeInT',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
