# Generated by Django 2.0.2 on 2018-10-24 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squashApp', '0008_video_noplayers'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='player1Colour',
            field=models.CharField(default=1, max_length=50, verbose_name='playerColour'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='video',
            name='player2Colour',
            field=models.CharField(default=1, max_length=50, verbose_name='playerColour'),
            preserve_default=False,
        ),
    ]
