# Generated by Django 2.0.2 on 2018-10-25 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squashApp', '0010_auto_20181025_1343'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='uploadedBy',
            field=models.CharField(default=1, max_length=150, verbose_name='uploadedBy'),
            preserve_default=False,
        ),
    ]
