# Generated by Django 2.0.2 on 2018-08-31 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squashApp', '0002_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='player1',
            field=models.CharField(default=1, max_length=500, verbose_name='player1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='video',
            name='player2',
            field=models.CharField(default=2, max_length=500, verbose_name='player2'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='video',
            name='name',
            field=models.CharField(max_length=500, verbose_name='Title'),
        ),
    ]
