# Generated by Django 2.0.2 on 2018-09-04 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('squashApp', '0002_playerdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='player1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player1', to='squashApp.playerData'),
        ),
        migrations.AlterField(
            model_name='video',
            name='player2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player2', to='squashApp.playerData'),
        ),
    ]
