# Generated by Django 2.0.2 on 2018-08-31 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('squashApp', '0003_auto_20180831_1058'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='name',
            new_name='title',
        ),
    ]
