# Generated by Django 2.0.2 on 2018-08-31 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squashApp', '0004_auto_20180831_1112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='title',
            field=models.CharField(max_length=500, verbose_name='title'),
        ),
    ]
