# Generated by Django 2.0.2 on 2018-10-12 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squashApp', '0005_videodata_processedvideofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videodata',
            name='player1HeatMapVideoFile',
        ),
        migrations.RemoveField(
            model_name='videodata',
            name='player1StringLineVideoFile',
        ),
        migrations.RemoveField(
            model_name='videodata',
            name='player2HeatMapVideoFile',
        ),
        migrations.RemoveField(
            model_name='videodata',
            name='player2StringLineVideoFile',
        ),
        migrations.AlterField(
            model_name='videodata',
            name='player1HeatMapImage',
            field=models.FileField(null=True, upload_to='processedImages/', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='videodata',
            name='player1StringLineImage',
            field=models.FileField(null=True, upload_to='processedImages/', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='videodata',
            name='player2HeatMapImage',
            field=models.FileField(null=True, upload_to='processedImages/', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='videodata',
            name='player2StringLineImage',
            field=models.FileField(null=True, upload_to='processedImages/', verbose_name=''),
        ),
    ]
