# Generated by Django 2.0.2 on 2018-08-31 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squashApp', '0005_auto_20180831_1125'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='title',
        ),
        migrations.AddField(
            model_name='video',
            name='name',
            field=models.CharField(default=1, max_length=500, verbose_name='name'),
            preserve_default=False,
        ),
    ]
