# Generated by Django 2.0.2 on 2018-10-13 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squashApp', '0007_auto_20181012_1256'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='noPlayers',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
